### ISSUE TITLE
Validation: Number of files per entry in DirectObservation folder

### ISSUE THREAD

**Issue by MatthewAlmeida** [MatthewAlmeida/CS682ActivityRecognitionTF#1]
One necessary validation step:  Make sure that each entry referenced in the direct observation folder has complete data, meaning there are 5 corresponding csv files, RA / RW / LA / LW / Hip.

**Comment by aovladi** [comment]
We have 1 entry, where all 5 corresponding files are missing, and 1 entry where we have an extra RA file, but it corresponds to a different date. So in terms of our project, I think we can eliminate these 2 files. Additionally, we don't have enough direct observation files.
