### ISSUE TITLE
Validation: Determine Target distribution

### ISSUE THREAD

**Issue by MatthewAlmeida** [MatthewAlmeida/CS682ActivityRecognitionTF#3]
We will need to understand the distribution of our targets in order to properly evaluate our model's performance.  If possible, I'd like us to know the distribution of the targets with respect to both 1) number of sample sequences (basically, someone doing something) and 2) activity time performed - let's figure out how much total time we have by class label.

**Comment by justerxiao** [comment]
I am working on this part and report it to you when I have results.
